// Generated by Noxus types 
export class CharacterBaseCharacteristic{
constructor(base,additionnal,objectsAndMountBonus,alignGiftBonus,contextModif) {
this.protocolId  = 4;
this.base = base;
this.additionnal = additionnal;
this.objectsAndMountBonus = objectsAndMountBonus;
this.alignGiftBonus = alignGiftBonus;
this.contextModif = contextModif;
}
serialize(buffer){
         buffer.writeVarShort(this.base);
         buffer.writeVarShort(this.additionnal);
         buffer.writeVarShort(this.objectsAndMountBonus);
         buffer.writeVarShort(this.alignGiftBonus);
         buffer.writeVarShort(this.contextModif);
}
deserialize(buffer){
         this.base = buffer.readVarShort();
         this.additionnal = buffer.readVarShort();
         this.objectsAndMountBonus = buffer.readVarShort();
         this.alignGiftBonus = buffer.readVarShort();
         this.contextModif = buffer.readVarShort();
}
}
