module.exports = {
        ACTION_BUY_SELL : 1,
		ACTION_EXCHANGE:2,
		ACTION_TALK:3,
		ACTION_DROP_COLLECT_PET:4,
		ACTION_SELL:5,
		ACTION_BUY:6,
		ACTION_RESURRECT_PET:6,
		ACTION_TRADE_MOUNT:7,
		ACTION_VIEW_HOUSES:8,
		ACTION_VIEW_PADDOCK:9
};