module.exports = {
    PIEGE_SOURNOIS: 65,
    POISON_INSIDIEUX: 66,
    PULSION_DE_CHAKRA:75,
    PIEGE_DE_MASSE:79,
    INVISIBILITE_AUTRUI:78,
    PIEGE_EMPOISONNE: 71,
    PIEGE_IMMOBILISATION: 69,
    PIEGE_SILENCE: 77,
    PIEGE_REPULSIF: 73,
    PEUR: 67,
    PIEGE_MORTEL: 80
};